DEP-23 S3 설정 및 이미지 업로드/삭제 API 구현
depromeet/Ding-dong-BE pull request #19
Opened 2023-06-10 16:25 UTC by Sim-mi-gyeong

## 개요
- [DEP-23](https://darae0730.atlassian.net/jira/software/c/projects/DEP/issues/DEP-23?filter=allissues) 

## 작업사항
- S3 관련 설정 추가
- 이미지 업로드/삭제 API 추가 (오류 수정 포함) - 로컬에서 삭제 부분도 테스트 완료
- 이미지 업로드/삭제 로직 리팩토링

## 변경로직
- 주형님께서 추천해주신 [서비스 추상화](https://tecoble.techcourse.co.kr/post/2022-10-10-Service/) 참고해서 이미지 업로드/삭제 로직에 포함된 AmazonS3 인터페스를 구현하는 과정에서 사용하는 메서드에 대해 서비스 추상화를 적용해보았습니당

* 바로 앞에 주형님꼐서 올려주신 PR Merge 되면 DEV 브랜치 변경사항 DEP-23 브랜치로 merge 해놓겠습니당

2023-06-11 04:44 UTC, sanbonai06 commented on Infrastructure/src/main/java/com/dingdong/infrastructure/config/s3/S3Config.java
> +    }
잘 돌아가서 행복

2023-06-11 04:48 UTC, sanbonai06 commented on Infrastructure/src/main/java/com/dingdong/infrastructure/s3/S3Api.java
> +    }
오 저희 서버에서 직접 업로드하는 방식으로 결정된건가용?

2023-06-11 04:53 UTC, sanbonai06 commented on Infrastructure/src/main/java/com/dingdong/infrastructure/s3/S3Service.java
> +    }
👍

2023-06-11 04:53 UTC, sanbonai06 approved these changes
LGTM 💯

2023-06-11 15:31 UTC, dkswnkk commented on Infrastructure/src/main/java/com/dingdong/infrastructure/config/s3/S3Config.java
> +    }
👍🏻

2023-06-11 15:32 UTC, dkswnkk commented on Infrastructure/src/main/java/com/dingdong/infrastructure/s3/S3Api.java
> +    }
👍🏻

2023-06-11 15:47 UTC, dkswnkk requested changes

2023-06-11 15:47 UTC, dkswnkk commented on Infrastructure/src/main/java/com/dingdong/infrastructure/s3/S3Service.java
> +    private final S3Api s3Api;
요거 interface 써서 다시 한번 추상화에 대해서 생각해봐요 미경님 ^_^
cc. https://tecoble.techcourse.co.kr/post/2022-10-10-Service

cc. https://github.com/Walkhub/Walkhub-Server/blob/main/src/main/java/com/walkhub/walkhub/infrastructure/image/ImageUtil.java
cc. https://github.com/Walkhub/Walkhub-Server/blob/main/src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Facade.java

2023-06-12 12:28 UTC, dkswnkk commented
- 미경님이 작업하셨던 https://github.com/depromeet/Ding-dong-BE/pull/19/commits/49dadf9b99c5e4a404f332db238e21159638fd9c, https://github.com/depromeet/Ding-dong-BE/pull/19/commits/97925bc0502be7aae07c13eb2881b1c267d604b5 에서 https://github.com/depromeet/Ding-dong-BE/pull/19/commits/f9c62d21239a5103453f256596ee0296f7fffe32 이렇게 조금 더 추상화 시켜봤어요 

cc. https://tecoble.techcourse.co.kr/post/2021-11-21-dip/
cc. [5번째 문단, DIP](https://dkswnkk.tistory.com/550)

```DIP(Dependency Inversion Principle)이란 의존 관계를 역전시켜서 저수준 모듈이 고수준 모듈에 의존하도록 구현하는 것을 의미합니다. 고수준 모듈이 저수준 모듈을 직접 의존하는 것이 아니라, 저수준 모듈이 인터페이스 등 추상을 매개체로 고수준 모듈을 참조하도록 합니다. 이를 통해 구현 기술과 관련된 종속성을 쉽게 제거할 수 있습니다.```
=> 간단하게 말하면 구현체가 아니라 인터페이스에 의존하는 것을 의미합니다.

## 추상화 X
![image](https://github.com/depromeet/Ding-dong-BE/assets/74492426/7e68b730-5370-4306-b33c-d8bea7661cee)

## 추상화 O
![image](https://github.com/depromeet/Ding-dong-BE/assets/74492426/6071a8c5-fcdc-4a66-955d-e812f90d7717)

위처럼 자동차가 구체적인 타이어가 아닌 추상화된 타이어 인터페이스에만 의존하게 함으로써 타이어가 변경되더라도 자동차가 영향을 받지 않게 구현함으로써 의존관계 역전 원칙을 지킬 수 있습니다.

2023-06-12 12:31 UTC, dkswnkk approved these changes

2023-06-12 14:42 UTC, merged