DEP-76: 관리자 행성 만들기 / 관리 API
depromeet/Ding-dong-BE pull request #27
Opened 2023-06-14 19:55 UTC by Sim-mi-gyeong

## 개요
- [DEP-76: 관리자 행성 만들기 / 관리 API](https://darae0730.atlassian.net/browse/DEP-76)

## 작업사항
- 행성 만들기 API
  - 행성의 고유 초대코드는 알파벳 + 숫자 조합 6자리
  - 행성을 만든 사용자 = 관리자 처리
    - 이후에 관리자가 추가될수도 있는지, 그렇다면 관리자 추가와 관련된 API 작업이 필요할지 확인 필요! 
- 행성 관리(꾸미기/수정) API 
  - 행성 만들기에서 등록한 행성 이름/로고 이미지, 행성 만들기에서 등록한 내용 수정 및 등록되지 않은 배경 이미지/소개 추가 가능
  - 행성 관리자 권한만 수정 가능

## 변경로직
- 수정 API 에 대해서 PUT 적용하기로 하여 수정하였습니당
- 질문,, 
  - 현재 [행성을 만들고 -> 그 행성의 관리자 목록에 행성을 만든 사용자 추가] 의 흐름으로 구현되어 있는데요, 
  - 애초에 Community 객체를 생성할 때 관리자 목록에 해당 유저를 추가하도록 팩토리 메서드를 수정할지 고민입니당 
  - (저희 도메인 설계 당시에 추가된 기존의 팩토리 메서드를 유지한채로 우선 해놨어요)

2023-06-15 13:33 UTC, sanbonai06 commented on Api/src/main/java/com/dingdong/api/community/controller/CommunityController.java
> +        return communityService.createCommunity(request);
서비스에선 dto 리턴 => 컨트롤러에선 response로 묶어서 리턴하기로 해서 바꿔주시면 좋을거 같아용

2023-06-15 13:34 UTC, sanbonai06 commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +                        userHelper.getCurrentUser()));
한방 로직 멋있네여

2023-06-15 13:35 UTC, sanbonai06 commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    }
열심히 만들었는데... 눙물

2023-06-15 13:35 UTC, sanbonai06 commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    }
그런데 나중에도 쓸 수 있으니 놔두는게 어떨까 싶네용

2023-06-15 13:37 UTC, sanbonai06 commented on Domain/src/main/java/com/dingdong/domain/domains/community/adaptor/CommunityAdaptor.java
> +    }
adaptor에는 repository 메서드를 직접적으로 쓰는 로직들만 있는게 좋을거 같아용
community에 admin 추가 로직은 뭔가 Community Entity가 가지고 있는게 맞을 거 같아용 (제 개인 의견임)

2023-06-15 13:38 UTC, sanbonai06 commented on Domain/src/main/java/com/dingdong/domain/domains/community/adaptor/CommunityAdaptor.java
> +    public void update(String name, CommunityImage communityImage, String description) {}
위에 어드민 추가 로직이랑 같이 entity 클래스가 관리하는게 어떨까용

2023-06-15 13:38 UTC, sanbonai06 commented on Domain/src/main/java/com/dingdong/domain/domains/community/domain/Community.java
>      }
어라 여기있네요 그럼 저 위에 있는건 뭐지

2023-06-15 13:39 UTC, sanbonai06 approved these changes
고생하셨습니당! LGTM

2023-06-15 14:57 UTC, dkswnkk requested changes
고생하셨어용, 조금 더 고민할 수 있는 부분이 보여 리뷰 남겼습니당 화이팅입니다!

2023-06-15 14:57 UTC, dkswnkk commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    private final int MAX_RETRY = 10;
매직 넘버 처리 굿!
다만 static으로 되어야 할 것 같네용~!

2023-06-15 14:57 UTC, dkswnkk commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    public Community findAndValidateCommunity(Long communityId) {
현재 요 클래스에서만 쓰이고 있는데 private로 해도 될듯용~!

추가로 ```findAndValidateCommunity```는 메서드 명이 "찾고 행성을 검증하다"라는 느낌인데, 실제 작업은 유저가 관리자인지도 검증하는 로직이 있어서 ```findAndValidateAdminUserInCommunity```은 어떨까 추천드립니당

2023-06-15 14:57 UTC, dkswnkk commented on Domain/src/main/java/com/dingdong/domain/domains/community/adaptor/CommunityAdaptor.java
> +    }
저도 민준님이랑 동일한 생각입니당

2023-06-15 14:57 UTC, dkswnkk commented on Domain/src/main/java/com/dingdong/domain/domains/community/adaptor/CommunityAdaptor.java
> +    public void update(String name, CommunityImage communityImage, String description) {}
저도 이런 것들은 도메인에서 관리하는게 좋다고 생각합니다.

2023-06-15 14:57 UTC, dkswnkk commented on Domain/src/main/java/com/dingdong/domain/domains/community/domain/Community.java
> +        return this.communityImage.getLogoImageUrl();
- https://github.com/depromeet/Ding-dong-BE/pull/24
- https://github.com/depromeet/Ding-dong-BE/blob/4bd1346b6454f7d2616d4c3786ffd13d988bb535/Domain/src/main/java/com/dingdong/domain/domains/id
card/domain/entity/IdCard.java#L66

여기서 제가 의도적으로 추가했는데 null check 롤백한 이유가 있나용?

2023-06-15 14:57 UTC, dkswnkk commented on Domain/src/main/java/com/dingdong/domain/domains/community/domain/Community.java
>      }
술 드신 상태로 작성하신거 같네요

2023-06-15 14:57 UTC, dkswnkk commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    }
고생했어용~!

다만 좀 더 개선점을 드리자면 코드 생성은 `전략패턴(strategy pattern)`을 사용해서 작성해보는게 어떨까 싶네요

- https://programmer-ririhan.tistory.com/389
- https://pjh3749.tistory.com/249
- https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/

지금은 저희가 테스트 코드를 작성하지 않지만 만약 테스트 코드를 작성한다고 생각했을 때, 지금과 같은 랜덤 생성 부분은 테스트를 하기가 굉장히 어렵습니다. 이때 전략 패턴을 사용하면 런타임시에 객체 내부에서 사용될 로직을 주입할 수 있어서 테스트하기가 용이합니다.

예를 들어서 번호 생성 Interface가 있고, 자동 생성 구현체와, 수동 생성 구현체를 만들어 놓으면 테스트 코드에서는 수동 생성 구현체를 주입하여 테스트할 수 있겠죵?

2023-06-15 14:57 UTC, dkswnkk commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    private String generateRandomAlphanumericCode() {
요런것들도 CommunityService가 가지고 있어야 할 책임은 아니라고 생각됩니당

2023-06-15 15:37 UTC, Sim-mi-gyeong commented on Domain/src/main/java/com/dingdong/domain/domains/community/domain/Community.java
>      }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 오잉.. 진짜 이거 뭐지.. 왜 이게 있지...ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-06-15 15:38 UTC, Sim-mi-gyeong commented on Api/src/main/java/com/dingdong/api/community/controller/CommunityController.java
> +        return communityService.createCommunity(request);
오옹 넹 요건 쿰척쿰척 수정하겠습니당~!

2023-06-15 15:51 UTC, Sim-mi-gyeong commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    }
오옹 넹넹 레퍼런스 참고해서 개선해보도록 하겠습니다!!!

2023-06-15 15:52 UTC, Sim-mi-gyeong commented on Domain/src/main/java/com/dingdong/domain/domains/community/adaptor/CommunityAdaptor.java
> +    public void update(String name, CommunityImage communityImage, String description) {}
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ넵^__^

2023-06-15 15:52 UTC, Sim-mi-gyeong commented on Domain/src/main/java/com/dingdong/domain/domains/community/adaptor/CommunityAdaptor.java
> +    }
넹 좋아용!!! 말씀주신 부분 반영하겠습니닷!!

2023-06-15 15:55 UTC, Sim-mi-gyeong commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    public Community findAndValidateCommunity(Long communityId) {
오,, 네이밍 좋아욥!-! 접근 제한자 수정 + 네이밍 변경 가겠습니닷~!

2023-06-15 15:57 UTC, Sim-mi-gyeong commented on Domain/src/main/java/com/dingdong/domain/domains/community/domain/Community.java
> +        return this.communityImage.getLogoImageUrl();
엇 이게 뭐지,, 따로 건들인 거 없었는데🧐 
제가 작업하던 도중에 주형님 작업 내용 dev에서 merge 해오면서 충돌이 생겼는지 어쩌다가 요렇게 된 것 같아유🥺 
요건 다시 돌려놓겠습니닷!

2023-06-15 15:58 UTC, Sim-mi-gyeong commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    private String generateRandomAlphanumericCode() {
넵!!!!!! 전략패턴 적용해서 수정해볼게용!!!

2023-06-15 16:13 UTC, sanbonai06 commented on Api/src/main/java/com/dingdong/api/community/service/CommunityService.java
> +    }
공부가 되는 리뷰 좋아용

2023-06-18 10:11 UTC, Sim-mi-gyeong reviewed
@dkswnkk 주형님께서 피드백 주신 부분에 대해 전략 패턴을 적용하여 초대 코드 발번 로직을 수정해보았는데용,,

초대 코드 발번 로직 단계가 아래와 같고

> 1. 랜덤한 6자리 숫자 + 알파벳 조합의 문자열 생성
> 2. 현재 다른 행성의 초대 코드와 중복되지 않은지 체크

2번에서 중복되지 않은 코드인 경우 해당 코드를 그 행성의 초대 코드로 저장하게 됩니다!

----
주형님께서 말씀주신 초대 코드를 생성하는 부분이 CommunityService 가 가지고 있을 책임은 아니다 라는 말에 동의를 합니다. 그래서 최대한 코드를 생성하고 중복 체크 하는 부분을 Generator 인터페이스에 정의하고, 구현체에서 구현하도록 했습니다.

- 만약, 테스트를 위해 랜덤한 코드를 생성하지 않고, 설정한 값으로 생성하고자 하는 경우 Generator 인터페이스의 구현체로 NonRandomCodeGenertor 를 두면 될 것 같아요!

----

그런데, '**다른 행성의 초대 코드와 중복되지 않은지 체크**' 하는 부분의 경우 **`CodeGenerator`** 에서 수행하는 것이 맞는지,, 확신이 없어서요ㅠㅅㅠ 

만약 NonRandomCodeGenertor 를 통해 수동으로 초대 코드를 생성(지정) 하도록 하더라도 다른 행성의 초대 코드와의 중복 체크는 필요할 것으로 보여요!..! 
- 예를 들면 MAX_RETRY = 10 이니까, 10개의 초대 코드 리스트를 생성해서 자동 발번 로직과 같은 단계를 진행한다던지?

최대한 **초대 코드를 생성하는 부분을 CommunityService 에서 덜어내려고** 했는데,, 이렇게 하는게 맞는 것인지 잘 모르겠어서 피드백 요청드립니당🥺😭

@sanbonai06 민준님도 피드백 해주시면 너무너무너무 감사할 것 같아요오🥺

----

현재 commit 에서 RandomCodeGenerator 의 생성자 주입으로 CommunityAdaptor 가 들어가 있는데 다음 커밋 내역에서 CommunityValidator 로 변경했습니다!

2023-06-18 12:56 UTC, dkswnkk commented
```stragegy interface```에 굳이 메서드를 두개 둘 필요가 없다고 생각해용
domains.community.domain.strategy 패키지에 아래와 같은 메서드를 하나가진 함수형 인터페이스를 생성하고,
```java
package com.dingdong.domain.domains.community.domain.strategy;

@FunctionalInterface
public interface GenerateCommunityInvitationCodeStrategy {
    String generate();
}
```

community.service.generator에 아래와 같은 명칭으로 구현체를 만들면 될 것 같아요!
```java
package com.dingdong.api.community.service.generator;


import com.dingdong.domain.domains.community.domain.strategy.GenerateCommunityInvitationCodeStrategy;
import lombok.RequiredArgsConstructor;
import org.apache.commons.lang3.RandomStringUtils;

@RequiredArgsConstructor
public class RandomCommunityCodeGeneratorStrategy implements GenerateCommunityInvitationCodeStrategy {

    private static final int CODE_LENGTH = 6;

    @Override
    public String generate() {
        return RandomStringUtils.randomAlphanumeric(CODE_LENGTH);
    }

}
```


> 그런데, '다른 행성의 초대 코드와 중복되지 않은지 체크' 하는 부분의 경우 CodeGenerator 에서 수행하는 것이 맞는지,, 확신이 없어서요ㅠㅅㅠ

그리고 위 질문 주신 것에 대해서 제 생각은 CodeGenerator에서 수행되는 것이 저는 더 맞다고 생각됩니다!
하지만 현재 미경님이 작성하신 로직으로 간다면 CodeGenerator에서 CommunityAdaptor를 의존해야 한다는 문제점이 있는데용 차라리 CommunityService에서 모든 행성의 초대 코드를 조회한 후 담은 리스트를 Strategy 구현체에 넘겨서 중복을 체크하면은 의존 문제와 여러 번 조회 쿼리를 날려야 하는 문제점을 개선할 수 있지 않을까 싶네요

2023-06-18 12:56 UTC, dkswnkk commented on Domain/src/main/java/com/dingdong/domain/domains/community/validator/CommunityValidator.java
> +        if (!(isAdminUser(communityId, userId))) {
괄호 하나 벗겨도 될거같아요

2023-06-18 14:01 UTC, Sim-mi-gyeong reviewed
이전에 구현했던 방식에서는 제가 고민했던 부분인 구현체 클래스가 CommunityValidator를 의존하는 문제가 있었는데요,,
@dkswnkk 님이 의견주신대로 CommunityService 에서 전체 행성 코드를 넘겨서 체크를 하니 Generator 클래스에서 CommunityValidator 를 의존하지 않도록 수정할 수 있었습니다!.!

그리고 주형님께서 예시로 작성해주신 코드의 네이밍이 이 전략의 역할을 더 정확히 명시할 수 있다고 생각해서 네이밍도 수정했어요!

그리고 MAX_RETRY 라이 다른 방식의 초대 코드를 생성할 때에도 공통적으로 적용하도록 하기 위해서 CommunityService 에서 관리하였는데요, 현재로서는 이 값을 CommunityService 가 굳이 알고있을 필요는 없다고 생각해서 구현체 클래스로 넘겼습니닷🧐

2023-06-18 14:28 UTC, dkswnkk commented
크 고생하셨습니다 처음보다 코드들이 훨씬 깔끔해졌네용 ㅋㅋㅋ

정말 정말 마지막으로 현재 크게 생성 번호가 겹칠 가능성이 없어서 10번만 반복한다고 하셨는데, 정말 정말 혹시나 10번동안 중복된 코드가 나올경우 ""가 반환되어서 문제가 될 것 같아요 ㅎㅎ,,, while문으로 하는게 나을 것 같습니다.! 

또한 List를 HashSet으로 변환한 뒤 contains를 쓰면 find 시간복잡도도 O(1)로 줄어들 것 같아요!

```java
public class RandomCommunityCodeGeneratorStrategy implements GenerateCommunityInvitationCodeStrategy {

    private static final int CODE_LENGTH = 6;

    @Override
    public String generate(List<String> existingCodes) {
        Set<String> codesSet = new HashSet<>(existingCodes);
        String code;
        
        do {
            code = RandomStringUtils.randomAlphanumeric(CODE_LENGTH);
        } while (codesSet.contains(code));
        
        return code;
    }
}
```

2023-06-18 14:29 UTC, dkswnkk approved these changes

2023-06-18 14:35 UTC, Sim-mi-gyeong commented
맞아요ㅠㅠ.. 사실 슬랙에서 말씀드렸던 것처럼 현재 규모에서 10번 정도까지 retry 했을 때 중복되는 케이스는 발생하지 않을 것 같다,, 고 했지만 그래도 이 부분이 걸렸어요.. 그렇다고 while 로 했을 때 너무 많은 반복을 수행하지 않을까 하는 걱정에,, 
그래도 안전하게 최악의 상황을 커버할 수 있는 while 이 좋은 것 같아요!! 🥺 이렇게 랜덤으로 코드를 발번하는 로직 관련해서 저도 한 번 더 고민해보겠습니다!-!

그리고 List 문자열을 체크하다보니 매번 O(N) 의 시간복잡도가 발생하긴 하겠다라고 생각만 하고 멈췄는데,,(반성중😭) HashSet 으로 변환까지🥺 꼼꼼하게 봐주셔서 너무너무너무 감사합니닷!!!!!!!!!!!!!! 👀

2023-06-18 15:01 UTC, merged